Update LICENSE file
canonical/tdx pull request #110
Opened 2024-05-17 08:15 UTC by hector-cao

Move to GPLv3 to be compliant with Canonical licensing policy

2024-05-17 22:53 UTC, bktan8 approved these changes
LGTM

2024-05-20 17:51 UTC, frenchwr commented on attestation/check-production.sh
> +# This file is part of tdx repo. See LICENSE file for license information.
Should we write something more specific in the two sentences at the bottom? Or has this wording already been developed/approved by the powers at be? I'm thinking something like the following: "This file is part of Canonical's TDX GitHub repository (https://github.com/canonical/tdx). See the LICENSE file in the repository for license information."

2024-05-21 21:55 UTC, chrisschnabel requested changes
1. The copyright date should be the date the file was first released. I believe that this is 2023 in most cases?
2. I agree with @frenchwr regarding specifying Canonical TDX 
3. It should include the boilerplate about warranty, etc...

I think I've generally addressed with this text, provided all Copyright are 2023:

This file is part of Canonical's TDX repository, available at https://github.com/canonical/tdx, which includes tools to setup and configure a confidential computing environment based on Intel TDX technology. See the LICENSE file in the repository for license information.

Copyright 2023 Canonical Ltd.

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License version 3, as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranties of MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

2024-05-22 08:02 UTC, hector-cao commented
> This file is part of Canonical's TDX repository, available at https://github.com/canonical/tdx, which includes tools to setup and configure a confidential computing environment based on Intel TDX technology. See the LICENSE file in the repository for license information.
> 
> Copyright 2023 Canonical Ltd.
> 
> This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License version 3, as published by the Free Software Foundation.
> 
> This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranties of MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
> 
> You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.

Thanks @chrisschnabel 
1) For the year, i think that is fine to use 2024 since this is for 24.04 release
2) Ok for the boilerplate but i m wondering if putting the link to GH canonical is a good idea, that will create an unnecessary dependancy that will need to be maintained for the long run

What do you think ?

2024-05-27 11:43 UTC, zvr-intel commented on guest-tools/image/create-td-image.sh
> +# See LICENSE.apache file for license information.
```suggestion
# See LICENSE.apache file for original license information.
```

2024-06-03 10:18 UTC, zvr-intel commented
I would also suggest you add an SPDX license identifier line.

Taking all previous discussion into account, the header could look like:

```
# This file is part of Canonical's TDX repository which includes tools
# to setup and configure a confidential computing environment
# based on Intel TDX technology.
# See the LICENSE file in the repository for the license text.

# Copyright 2024 Canonical Ltd.
# SPDX-License-Identifier: GPL-3.0-only

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranties
# of MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
```

2024-06-10 20:32 UTC, chrisschnabel commented
@hector-cao the changes that @zvr-intel proposes are also good ones: i.e. add 'original' when pointing to the Apache license; and add SPDX license identifier line.

2024-06-24 15:18 UTC, merged