PEK 850: Adding part of the higher priority tests
canonical/tdx pull request #165
Opened 2024-07-18 17:06 UTC by spmcmillan

Adding tests to tdx set.  Still need to add to checkbox tests in a separate PR with the rest of the tests specified in PEK850 in next pulse.

2024-07-19 10:59 UTC, hector-cao requested changes

2024-07-19 10:59 UTC, hector-cao commented on tests/tests/test_guest_fail.py
> +    cs = subprocess.run(['sudo', 'rmmod', 'kvm_intel'], check=True)
the rmmod will fail if there is any VM running, `rmmod: ERROR: Module kvm_intel is in use` ; i dont know how we can  handle this situation

2024-09-12 14:36 UTC, spmcmillan reviewed
LGTM, I didn't approve yet because of the init command pending item, but will if that is ok

2024-09-12 14:37 UTC, spmcmillan commented on tests/tests/setup-env-tox.sh
> +  sudo rmmod kvm_intel
It says in the comment, but we load it differently at times on the different tests.  So, this is to make sure we load it the same way at the beginning of each test.

2024-09-12 14:40 UTC, hector-cao commented on tests/tests/test_guest_cpu_off.py
> +        m.check_exec('sudo init 0 &')
ok great, thanks

2024-09-12 14:42 UTC, hector-cao commented on tests/tests/setup-env-tox.sh
> +  sudo rmmod kvm_intel
ideally, each test should reload the kernel module properly if it previously unloaded it, but in practice, if there is any reason you cannot have this certainty, loading it in the tox global setup will not be enough, we have to make sure to do it at the beginning of each test. So i think, for now, i will go for the ideal situation where each test should unload/reload the kernel module properly

2024-09-12 15:14 UTC, spmcmillan commented on tests/tests/setup-env-tox.sh
> +  sudo rmmod kvm_intel
true and agreed

2024-09-13 07:30 UTC, merged