Display login information of non-root user in addition to root user
canonical/tdx pull request #254
Opened 2024-10-24 11:39 UTC by TejaswineeL

### Description of the changes
Currently, `run_td.sh `shows `ssh `command only for root user.
It does not show TD login information for the default user.
It also does not show TD login information for customized TD guest user(specified during TD image creation)

### How to test this PR?
1. Please follow the instructions given [here](https://github.com/canonical/tdx/tree/noble-24.04?tab=readme-ov-file#51-create-a-new-td-image) to create a TD image.
2. Follow the instructions given [here](https://github.com/canonical/tdx/tree/noble-24.04?tab=readme-ov-file#61-boot-td-with-qemu) to boot the TD with qemu.
3. TD login information with `ssh`commands will be displayed

2024-10-30 13:24 UTC, hector-cao requested changes

2024-10-30 13:24 UTC, hector-cao commented on guest-tools/run_td.sh
> +The default non-root user is tdx
```suggestion
The default non-root user is `tdx`
```

2024-11-04 07:00 UTC, TejaswineeL commented on guest-tools/run_td.sh
> +The default non-root user is tdx
done

2024-11-04 07:01 UTC, TejaswineeL commented on guest-tools/run_td.sh
> +To login with a non-root user, specified during the creation of
done

2024-11-04 07:03 UTC, TejaswineeL commented
I rebased the branch

2024-11-04 08:28 UTC, hector-cao approved these changes

2024-11-05 23:35 UTC, merged